version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - '${APP_DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
    wordpress:
        depends_on:
            - db
        image: maksim1990/wordpress_portfolio:latest
        ports:
            - "${APP_WORDPRESS_PORT}:80"
        restart: always
        container_name: wordpress_app
        volumes:
            - ./wordpress:/var/www/html
        environment:
            WORDPRESS_DB_HOST: ${DB_HOST}
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
            WORDPRESS_DB_NAME: ${DB_NAME}